apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-zwwbce
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-zwwbce
    app.kubernetes.io/part-of: jvm-build-suite-application-dfyy
  name: jvm-build-suite-component-zwwbce
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-zwwbce
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-zwwbce
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/jvm-build-bhoi-tenant/jvm-build-suite-application-dfyy/jvm-build-suite-component-zwwbce@sha256:dd5c0b8852775279270221431e7293ccd3175233aabff159b110836b3c5f4943
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
